-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_elem_data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_elem_data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_elem_data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_elem_data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_0_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_0_V_full_n : IN STD_LOGIC;
    res_stream_V_data_0_V_write : OUT STD_LOGIC;
    res_stream_V_data_1_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_1_V_full_n : IN STD_LOGIC;
    res_stream_V_data_1_V_write : OUT STD_LOGIC;
    res_stream_V_data_2_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_2_V_full_n : IN STD_LOGIC;
    res_stream_V_data_2_V_write : OUT STD_LOGIC;
    res_stream_V_data_3_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_3_V_full_n : IN STD_LOGIC;
    res_stream_V_data_3_V_write : OUT STD_LOGIC;
    res_stream_V_data_0_V_blk_n : OUT STD_LOGIC;
    res_stream_V_data_1_V_blk_n : OUT STD_LOGIC;
    res_stream_V_data_2_V_blk_n : OUT STD_LOGIC;
    res_stream_V_data_3_V_blk_n : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal kernel_data_V_1_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_19 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_20 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_21 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_22 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_23 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_28 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_29 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_30 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_31 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_32 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_33 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_34 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal kernel_data_V_1_35 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal sX_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sY_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pX_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal or_cond4_reg_1084 : STD_LOGIC_VECTOR (0 downto 0);
    signal kernel_data_V_1_s_reg_904 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_1_reg_909 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_2_reg_914 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_3_reg_919 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_4_1_reg_924 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_5_1_reg_929 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_6_1_reg_934 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_7_1_reg_939 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_8_1_reg_944 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_9_1_reg_949 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_10_1_reg_954 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_4_1_1_reg_959 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_4_ret_reg_964 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_5_ret_reg_969 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_6_ret_reg_974 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_7_ret_reg_979 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_8_ret_reg_984 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_9_ret_reg_989 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_10_ret_reg_994 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_11_ret_reg_999 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_16_ret_reg_1004 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_17_ret_reg_1009 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_18_ret_reg_1014 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_19_ret_reg_1019 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_20_ret_reg_1024 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_21_ret_reg_1029 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_22_ret_reg_1034 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_23_ret_reg_1039 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_28_ret_reg_1044 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_29_ret_reg_1049 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_30_ret_reg_1054 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_31_ret_reg_1059 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_32_ret_reg_1064 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_33_ret_reg_1069 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_34_ret_reg_1074 : STD_LOGIC_VECTOR (15 downto 0);
    signal kernel_data_V_1_35_ret_reg_1079 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_cond4_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_795_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_reg_1088 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_in_fu_819_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_in_reg_1092 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_56_fu_839_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_reg_1097 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_in2_fu_863_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_in2_reg_1101 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_out_0_V_reg_1106 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal res_out_1_V_reg_1111 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_2_V_reg_1116 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_out_3_V_reg_1121 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_done : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_idle : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ready : STD_LOGIC;
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_start : STD_LOGIC;
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_done : STD_LOGIC;
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_idle : STD_LOGIC;
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ready : STD_LOGIC;
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_16 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_17 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_18 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_19 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_20 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_21 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_22 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_23 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_24 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_25 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_26 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_27 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_28 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_29 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_30 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_31 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_32 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_33 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_34 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_35 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ce : STD_LOGIC;
    signal storemerge_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal res_stream_V_data_0_V1_update : STD_LOGIC;
    signal res_stream_V_data_0_V1_status : STD_LOGIC;
    signal ap_block_state8 : BOOLEAN;
    signal tmp_58_fu_845_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_57_fu_801_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_460_fu_741_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_461_fu_761_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_s_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_751_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp7_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_783_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_777_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_fu_813_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal phitmp2_fu_857_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_98 : BOOLEAN;
    signal ap_condition_1898 : BOOLEAN;
    signal ap_condition_1902 : BOOLEAN;
    signal ap_condition_1897 : BOOLEAN;
    signal ap_condition_1908 : BOOLEAN;

    component dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_16_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_18_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_19_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_20_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_21_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_22_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_24_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_27_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_28_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_29_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_30_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_31_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_32_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_33_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_34_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        data_35_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_elem_data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        in_elem_data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        in_elem_data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        in_elem_data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_10_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_11_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_16_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_17_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_18_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_19_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_20_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_21_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_22_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_23_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_28_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_29_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_30_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_31_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_32_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_33_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_34_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        kernel_window_35_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_32 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_33 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_34 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_35 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217 : component dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start,
        ap_done => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_done,
        ap_idle => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_idle,
        ap_ready => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ready,
        data_0_V_read => kernel_data_V_1_4_1_1_reg_959,
        data_1_V_read => kernel_data_V_1_10_1_reg_954,
        data_2_V_read => kernel_data_V_1_9_1_reg_949,
        data_3_V_read => kernel_data_V_1_8_1_reg_944,
        data_4_V_read => kernel_data_V_1_4_ret_reg_964,
        data_5_V_read => kernel_data_V_1_5_ret_reg_969,
        data_6_V_read => kernel_data_V_1_6_ret_reg_974,
        data_7_V_read => kernel_data_V_1_7_ret_reg_979,
        data_8_V_read => kernel_data_V_1_8_ret_reg_984,
        data_9_V_read => kernel_data_V_1_9_ret_reg_989,
        data_10_V_read => kernel_data_V_1_10_ret_reg_994,
        data_11_V_read => kernel_data_V_1_11_ret_reg_999,
        data_12_V_read => kernel_data_V_1_7_1_reg_939,
        data_13_V_read => kernel_data_V_1_6_1_reg_934,
        data_14_V_read => kernel_data_V_1_5_1_reg_929,
        data_15_V_read => kernel_data_V_1_4_1_reg_924,
        data_16_V_read => kernel_data_V_1_16_ret_reg_1004,
        data_17_V_read => kernel_data_V_1_17_ret_reg_1009,
        data_18_V_read => kernel_data_V_1_18_ret_reg_1014,
        data_19_V_read => kernel_data_V_1_19_ret_reg_1019,
        data_20_V_read => kernel_data_V_1_20_ret_reg_1024,
        data_21_V_read => kernel_data_V_1_21_ret_reg_1029,
        data_22_V_read => kernel_data_V_1_22_ret_reg_1034,
        data_23_V_read => kernel_data_V_1_23_ret_reg_1039,
        data_24_V_read => kernel_data_V_1_3_reg_919,
        data_25_V_read => kernel_data_V_1_2_reg_914,
        data_26_V_read => kernel_data_V_1_1_reg_909,
        data_27_V_read => kernel_data_V_1_s_reg_904,
        data_28_V_read => kernel_data_V_1_28_ret_reg_1044,
        data_29_V_read => kernel_data_V_1_29_ret_reg_1049,
        data_30_V_read => kernel_data_V_1_30_ret_reg_1054,
        data_31_V_read => kernel_data_V_1_31_ret_reg_1059,
        data_32_V_read => kernel_data_V_1_32_ret_reg_1064,
        data_33_V_read => kernel_data_V_1_33_ret_reg_1069,
        data_34_V_read => kernel_data_V_1_34_ret_reg_1074,
        data_35_V_read => kernel_data_V_1_35_ret_reg_1079,
        ap_return_0 => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_0,
        ap_return_1 => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_1,
        ap_return_2 => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_2,
        ap_return_3 => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_3,
        ap_ce => grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ce);

    call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257 : component shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_start,
        ap_done => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_done,
        ap_idle => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_idle,
        ap_ready => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ready,
        in_elem_data_0_V_read => in_elem_data_0_V_read,
        in_elem_data_1_V_read => in_elem_data_1_V_read,
        in_elem_data_2_V_read => in_elem_data_2_V_read,
        in_elem_data_3_V_read => in_elem_data_3_V_read,
        kernel_window_4_V_read => kernel_data_V_1_4,
        kernel_window_5_V_read => kernel_data_V_1_5,
        kernel_window_6_V_read => kernel_data_V_1_6,
        kernel_window_7_V_read => kernel_data_V_1_7,
        kernel_window_8_V_read => kernel_data_V_1_8,
        kernel_window_9_V_read => kernel_data_V_1_9,
        kernel_window_10_V_read => kernel_data_V_1_10,
        kernel_window_11_V_read => kernel_data_V_1_11,
        kernel_window_16_V_read => kernel_data_V_1_16,
        kernel_window_17_V_read => kernel_data_V_1_17,
        kernel_window_18_V_read => kernel_data_V_1_18,
        kernel_window_19_V_read => kernel_data_V_1_19,
        kernel_window_20_V_read => kernel_data_V_1_20,
        kernel_window_21_V_read => kernel_data_V_1_21,
        kernel_window_22_V_read => kernel_data_V_1_22,
        kernel_window_23_V_read => kernel_data_V_1_23,
        kernel_window_28_V_read => kernel_data_V_1_28,
        kernel_window_29_V_read => kernel_data_V_1_29,
        kernel_window_30_V_read => kernel_data_V_1_30,
        kernel_window_31_V_read => kernel_data_V_1_31,
        kernel_window_32_V_read => kernel_data_V_1_32,
        kernel_window_33_V_read => kernel_data_V_1_33,
        kernel_window_34_V_read => kernel_data_V_1_34,
        kernel_window_35_V_read => kernel_data_V_1_35,
        ap_return_0 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_0,
        ap_return_1 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_1,
        ap_return_2 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_2,
        ap_return_3 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_3,
        ap_return_4 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_4,
        ap_return_5 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_5,
        ap_return_6 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_6,
        ap_return_7 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_7,
        ap_return_8 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_8,
        ap_return_9 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_9,
        ap_return_10 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_10,
        ap_return_11 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_11,
        ap_return_12 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_12,
        ap_return_13 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_13,
        ap_return_14 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_14,
        ap_return_15 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_15,
        ap_return_16 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_16,
        ap_return_17 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_17,
        ap_return_18 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_18,
        ap_return_19 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_19,
        ap_return_20 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_20,
        ap_return_21 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_21,
        ap_return_22 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_22,
        ap_return_23 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_23,
        ap_return_24 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_24,
        ap_return_25 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_25,
        ap_return_26 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_26,
        ap_return_27 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_27,
        ap_return_28 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_28,
        ap_return_29 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_29,
        ap_return_30 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_30,
        ap_return_31 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_31,
        ap_return_32 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_32,
        ap_return_33 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_33,
        ap_return_34 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_34,
        ap_return_35 => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_35,
        ap_ce => call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg <= ap_const_logic_0;
            else
                if (((or_cond4_fu_789_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_NS_fsm_state2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    pX_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_98)) then
                if ((tmp_55_fu_795_p2 = ap_const_lv1_1)) then 
                    pX_4 <= ap_const_lv32_0;
                elsif ((tmp_55_fu_795_p2 = ap_const_lv1_0)) then 
                    pX_4 <= tmp_57_fu_801_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                if ((ap_const_boolean_1 = ap_condition_1902)) then 
                    pY_4 <= ap_const_lv32_0;
                elsif ((ap_const_boolean_1 = ap_condition_1898)) then 
                    pY_4 <= tmp_58_fu_845_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_4_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_55_reg_1088 = ap_const_lv1_0))) then 
                    sX_4 <= p_in_reg_1092;
                elsif ((ap_const_boolean_1 = ap_condition_1897)) then 
                    sX_4 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    storemerge_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_1908)) then
                if ((tmp_56_reg_1097 = ap_const_lv1_1)) then 
                    storemerge_reg_206 <= ap_const_lv32_0;
                elsif ((tmp_56_reg_1097 = ap_const_lv1_0)) then 
                    storemerge_reg_206 <= p_in2_reg_1101;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                kernel_data_V_1_10 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_18;
                kernel_data_V_1_10_1_reg_954 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_1;
                kernel_data_V_1_10_ret_reg_994 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_18;
                kernel_data_V_1_11 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_19;
                kernel_data_V_1_11_ret_reg_999 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_19;
                kernel_data_V_1_16 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_20;
                kernel_data_V_1_16_ret_reg_1004 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_20;
                kernel_data_V_1_17 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_21;
                kernel_data_V_1_17_ret_reg_1009 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_21;
                kernel_data_V_1_18 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_22;
                kernel_data_V_1_18_ret_reg_1014 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_22;
                kernel_data_V_1_19 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_23;
                kernel_data_V_1_19_ret_reg_1019 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_23;
                kernel_data_V_1_1_reg_909 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_10;
                kernel_data_V_1_20 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_24;
                kernel_data_V_1_20_ret_reg_1024 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_24;
                kernel_data_V_1_21 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_25;
                kernel_data_V_1_21_ret_reg_1029 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_25;
                kernel_data_V_1_22 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_26;
                kernel_data_V_1_22_ret_reg_1034 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_26;
                kernel_data_V_1_23 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_27;
                kernel_data_V_1_23_ret_reg_1039 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_27;
                kernel_data_V_1_28 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_28;
                kernel_data_V_1_28_ret_reg_1044 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_28;
                kernel_data_V_1_29 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_29;
                kernel_data_V_1_29_ret_reg_1049 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_29;
                kernel_data_V_1_2_reg_914 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_9;
                kernel_data_V_1_30 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_30;
                kernel_data_V_1_30_ret_reg_1054 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_30;
                kernel_data_V_1_31 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_31;
                kernel_data_V_1_31_ret_reg_1059 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_31;
                kernel_data_V_1_32 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_32;
                kernel_data_V_1_32_ret_reg_1064 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_32;
                kernel_data_V_1_33 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_33;
                kernel_data_V_1_33_ret_reg_1069 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_33;
                kernel_data_V_1_34 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_34;
                kernel_data_V_1_34_ret_reg_1074 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_34;
                kernel_data_V_1_35 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_35;
                kernel_data_V_1_35_ret_reg_1079 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_35;
                kernel_data_V_1_3_reg_919 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_8;
                kernel_data_V_1_4 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_12;
                kernel_data_V_1_4_1_1_reg_959 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_0;
                kernel_data_V_1_4_1_reg_924 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_7;
                kernel_data_V_1_4_ret_reg_964 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_12;
                kernel_data_V_1_5 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_13;
                kernel_data_V_1_5_1_reg_929 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_6;
                kernel_data_V_1_5_ret_reg_969 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_13;
                kernel_data_V_1_6 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_14;
                kernel_data_V_1_6_1_reg_934 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_5;
                kernel_data_V_1_6_ret_reg_974 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_14;
                kernel_data_V_1_7 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_15;
                kernel_data_V_1_7_1_reg_939 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_4;
                kernel_data_V_1_7_ret_reg_979 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_15;
                kernel_data_V_1_8 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_16;
                kernel_data_V_1_8_1_reg_944 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_3;
                kernel_data_V_1_8_ret_reg_984 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_16;
                kernel_data_V_1_9 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_17;
                kernel_data_V_1_9_1_reg_949 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_2;
                kernel_data_V_1_9_ret_reg_989 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_17;
                kernel_data_V_1_s_reg_904 <= call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_return_11;
                or_cond4_reg_1084 <= or_cond4_fu_789_p2;
                tmp_55_reg_1088 <= tmp_55_fu_795_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (tmp_55_fu_795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_56_fu_839_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then
                p_in2_reg_1101 <= p_in2_fu_863_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_55_fu_795_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1))) then
                p_in_reg_1092 <= p_in_fu_819_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                res_out_0_V_reg_1106 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_0;
                res_out_1_V_reg_1111 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_1;
                res_out_2_V_reg_1116 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_2;
                res_out_3_V_reg_1121 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_return_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (tmp_55_reg_1088 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                sY_4 <= storemerge_reg_206;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (tmp_55_fu_795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                tmp_56_reg_1097 <= tmp_56_fu_839_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state8, or_cond4_reg_1084, ap_ce, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, res_stream_V_data_0_V1_status)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((or_cond4_reg_1084 = ap_const_lv1_1) and (res_stream_V_data_0_V1_status = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_block_state8_assign_proc : process(or_cond4_reg_1084, res_stream_V_data_0_V1_status)
    begin
                ap_block_state8 <= ((or_cond4_reg_1084 = ap_const_lv1_1) and (res_stream_V_data_0_V1_status = ap_const_logic_0));
    end process;


    ap_condition_1897_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_55_fu_795_p2)
    begin
                ap_condition_1897 <= ((tmp_55_fu_795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1));
    end process;


    ap_condition_1898_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_55_fu_795_p2, tmp_56_fu_839_p2)
    begin
                ap_condition_1898 <= ((tmp_55_fu_795_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_56_fu_839_p2 = ap_const_lv1_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_condition_1902_assign_proc : process(tmp_55_reg_1088, tmp_56_reg_1097, ap_CS_fsm_state2)
    begin
                ap_condition_1902 <= ((tmp_56_reg_1097 = ap_const_lv1_1) and (tmp_55_reg_1088 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;


    ap_condition_1908_assign_proc : process(ap_ce, tmp_55_reg_1088, ap_CS_fsm_state2)
    begin
                ap_condition_1908 <= ((ap_const_logic_1 = ap_ce) and (tmp_55_reg_1088 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;


    ap_condition_98_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
                ap_condition_98 <= ((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8, or_cond4_reg_1084, ap_ce, res_stream_V_data_0_V1_status)
    begin
        if (((not(((or_cond4_reg_1084 = ap_const_lv1_1) and (res_stream_V_data_0_V1_status = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state8)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8, or_cond4_reg_1084, ap_ce, res_stream_V_data_0_V1_status)
    begin
        if ((not(((or_cond4_reg_1084 = ap_const_lv1_1) and (res_stream_V_data_0_V1_status = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ce_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ce <= ap_const_logic_1;
        else 
            call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_start_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_start <= ap_const_logic_1;
        else 
            call_ret2_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config6_s_fu_257_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ce_assign_proc : process(ap_ce, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_ce) and ((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state7)))) then 
            grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ce <= ap_const_logic_1;
        else 
            grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config6_mult_0_0_0_0_0_fu_217_ap_start_reg;
    icmp7_fu_771_p2 <= "1" when (signed(tmp_461_fu_761_p4) > signed(ap_const_lv31_0)) else "0";
    icmp_fu_751_p2 <= "1" when (signed(tmp_460_fu_741_p4) > signed(ap_const_lv31_0)) else "0";
    or_cond4_fu_789_p2 <= (tmp_fu_777_p2 and tmp1_fu_783_p2);
    p_in2_fu_863_p3 <= 
        ap_const_lv32_1 when (tmp_52_fu_731_p2(0) = '1') else 
        phitmp2_fu_857_p2;
    p_in_fu_819_p3 <= 
        ap_const_lv32_1 when (tmp_s_fu_721_p2(0) = '1') else 
        phitmp_fu_813_p2;
    phitmp2_fu_857_p2 <= std_logic_vector(unsigned(sY_4) + unsigned(ap_const_lv32_1));
    phitmp_fu_813_p2 <= std_logic_vector(unsigned(sX_4) + unsigned(ap_const_lv32_1));
    res_stream_V_data_0_V1_status <= (res_stream_V_data_3_V_full_n and res_stream_V_data_2_V_full_n and res_stream_V_data_1_V_full_n and res_stream_V_data_0_V_full_n);

    res_stream_V_data_0_V1_update_assign_proc : process(ap_CS_fsm_state8, or_cond4_reg_1084, ap_ce, res_stream_V_data_0_V1_status)
    begin
        if ((not(((or_cond4_reg_1084 = ap_const_lv1_1) and (res_stream_V_data_0_V1_status = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_stream_V_data_0_V1_update <= ap_const_logic_1;
        else 
            res_stream_V_data_0_V1_update <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_0_V_blk_n_assign_proc : process(res_stream_V_data_0_V_full_n, ap_CS_fsm_state8, or_cond4_reg_1084)
    begin
        if (((or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_stream_V_data_0_V_blk_n <= res_stream_V_data_0_V_full_n;
        else 
            res_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_0_V_din <= res_out_0_V_reg_1106;
    res_stream_V_data_0_V_write <= res_stream_V_data_0_V1_update;

    res_stream_V_data_1_V_blk_n_assign_proc : process(res_stream_V_data_1_V_full_n, ap_CS_fsm_state8, or_cond4_reg_1084)
    begin
        if (((or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_stream_V_data_1_V_blk_n <= res_stream_V_data_1_V_full_n;
        else 
            res_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_1_V_din <= res_out_1_V_reg_1111;
    res_stream_V_data_1_V_write <= res_stream_V_data_0_V1_update;

    res_stream_V_data_2_V_blk_n_assign_proc : process(res_stream_V_data_2_V_full_n, ap_CS_fsm_state8, or_cond4_reg_1084)
    begin
        if (((or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_stream_V_data_2_V_blk_n <= res_stream_V_data_2_V_full_n;
        else 
            res_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_2_V_din <= res_out_2_V_reg_1116;
    res_stream_V_data_2_V_write <= res_stream_V_data_0_V1_update;

    res_stream_V_data_3_V_blk_n_assign_proc : process(res_stream_V_data_3_V_full_n, ap_CS_fsm_state8, or_cond4_reg_1084)
    begin
        if (((or_cond4_reg_1084 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            res_stream_V_data_3_V_blk_n <= res_stream_V_data_3_V_full_n;
        else 
            res_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_3_V_din <= res_out_3_V_reg_1121;
    res_stream_V_data_3_V_write <= res_stream_V_data_0_V1_update;
    tmp1_fu_783_p2 <= (icmp_fu_751_p2 and icmp7_fu_771_p2);
    tmp_460_fu_741_p4 <= pY_4(31 downto 1);
    tmp_461_fu_761_p4 <= pX_4(31 downto 1);
    tmp_52_fu_731_p2 <= "1" when (sY_4 = ap_const_lv32_2) else "0";
    tmp_55_fu_795_p2 <= "1" when (pX_4 = ap_const_lv32_26) else "0";
    tmp_56_fu_839_p2 <= "1" when (pY_4 = ap_const_lv32_1C) else "0";
    tmp_57_fu_801_p2 <= std_logic_vector(unsigned(pX_4) + unsigned(ap_const_lv32_1));
    tmp_58_fu_845_p2 <= std_logic_vector(unsigned(pY_4) + unsigned(ap_const_lv32_1));
    tmp_fu_777_p2 <= (tmp_s_fu_721_p2 and tmp_52_fu_731_p2);
    tmp_s_fu_721_p2 <= "1" when (sX_4 = ap_const_lv32_2) else "0";
end behav;
