// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_6u_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        in_elem_data_0_V_read,
        in_elem_data_1_V_read,
        in_elem_data_2_V_read,
        in_elem_data_3_V_read,
        res_stream_V_data_0_V_din,
        res_stream_V_data_0_V_full_n,
        res_stream_V_data_0_V_write,
        res_stream_V_data_1_V_din,
        res_stream_V_data_1_V_full_n,
        res_stream_V_data_1_V_write,
        res_stream_V_data_2_V_din,
        res_stream_V_data_2_V_full_n,
        res_stream_V_data_2_V_write,
        res_stream_V_data_3_V_din,
        res_stream_V_data_3_V_full_n,
        res_stream_V_data_3_V_write,
        res_stream_V_data_4_V_din,
        res_stream_V_data_4_V_full_n,
        res_stream_V_data_4_V_write,
        res_stream_V_data_5_V_din,
        res_stream_V_data_5_V_full_n,
        res_stream_V_data_5_V_write,
        res_stream_V_data_0_V_blk_n,
        res_stream_V_data_1_V_blk_n,
        res_stream_V_data_2_V_blk_n,
        res_stream_V_data_3_V_blk_n,
        res_stream_V_data_4_V_blk_n,
        res_stream_V_data_5_V_blk_n
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] in_elem_data_0_V_read;
input  [15:0] in_elem_data_1_V_read;
input  [15:0] in_elem_data_2_V_read;
input  [15:0] in_elem_data_3_V_read;
output  [15:0] res_stream_V_data_0_V_din;
input   res_stream_V_data_0_V_full_n;
output   res_stream_V_data_0_V_write;
output  [15:0] res_stream_V_data_1_V_din;
input   res_stream_V_data_1_V_full_n;
output   res_stream_V_data_1_V_write;
output  [15:0] res_stream_V_data_2_V_din;
input   res_stream_V_data_2_V_full_n;
output   res_stream_V_data_2_V_write;
output  [15:0] res_stream_V_data_3_V_din;
input   res_stream_V_data_3_V_full_n;
output   res_stream_V_data_3_V_write;
output  [15:0] res_stream_V_data_4_V_din;
input   res_stream_V_data_4_V_full_n;
output   res_stream_V_data_4_V_write;
output  [15:0] res_stream_V_data_5_V_din;
input   res_stream_V_data_5_V_full_n;
output   res_stream_V_data_5_V_write;
output   res_stream_V_data_0_V_blk_n;
output   res_stream_V_data_1_V_blk_n;
output   res_stream_V_data_2_V_blk_n;
output   res_stream_V_data_3_V_blk_n;
output   res_stream_V_data_4_V_blk_n;
output   res_stream_V_data_5_V_blk_n;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_stream_V_data_0_V_blk_n;
reg res_stream_V_data_1_V_blk_n;
reg res_stream_V_data_2_V_blk_n;
reg res_stream_V_data_3_V_blk_n;
reg res_stream_V_data_4_V_blk_n;
reg res_stream_V_data_5_V_blk_n;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
reg   [15:0] kernel_data_V_2_4;
reg   [15:0] kernel_data_V_2_5;
reg   [15:0] kernel_data_V_2_6;
reg   [15:0] kernel_data_V_2_7;
reg   [15:0] kernel_data_V_2_8;
reg   [15:0] kernel_data_V_2_9;
reg   [15:0] kernel_data_V_2_10;
reg   [15:0] kernel_data_V_2_11;
reg   [15:0] kernel_data_V_2_16;
reg   [15:0] kernel_data_V_2_17;
reg   [15:0] kernel_data_V_2_18;
reg   [15:0] kernel_data_V_2_19;
reg   [15:0] kernel_data_V_2_20;
reg   [15:0] kernel_data_V_2_21;
reg   [15:0] kernel_data_V_2_22;
reg   [15:0] kernel_data_V_2_23;
reg   [15:0] kernel_data_V_2_28;
reg   [15:0] kernel_data_V_2_29;
reg   [15:0] kernel_data_V_2_30;
reg   [15:0] kernel_data_V_2_31;
reg   [15:0] kernel_data_V_2_32;
reg   [15:0] kernel_data_V_2_33;
reg   [15:0] kernel_data_V_2_34;
reg   [15:0] kernel_data_V_2_35;
reg   [31:0] sX_3;
reg   [31:0] sY_3;
reg   [31:0] pY_3;
reg   [31:0] pX_3;
reg   [0:0] or_cond2_reg_1126;
reg   [15:0] kernel_data_V_2_s_reg_946;
reg    ap_block_state1_pp0_stage0_iter0;
wire    res_stream_V_data_0_V1_status;
reg    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] kernel_data_V_2_1_reg_951;
reg   [15:0] kernel_data_V_2_2_reg_956;
reg   [15:0] kernel_data_V_2_3_reg_961;
reg   [15:0] kernel_data_V_2_4_1_reg_966;
reg   [15:0] kernel_data_V_2_5_1_reg_971;
reg   [15:0] kernel_data_V_2_6_1_reg_976;
reg   [15:0] kernel_data_V_2_7_1_reg_981;
reg   [15:0] kernel_data_V_2_8_1_reg_986;
reg   [15:0] kernel_data_V_2_9_1_reg_991;
reg   [15:0] kernel_data_V_2_10_1_reg_996;
reg   [15:0] kernel_data_V_2_4_1_1_reg_1001;
reg   [15:0] kernel_data_V_2_4_ret_reg_1006;
reg   [15:0] kernel_data_V_2_5_ret_reg_1011;
reg   [15:0] kernel_data_V_2_6_ret_reg_1016;
reg   [15:0] kernel_data_V_2_7_ret_reg_1021;
reg   [15:0] kernel_data_V_2_8_ret_reg_1026;
reg   [15:0] kernel_data_V_2_9_ret_reg_1031;
reg   [15:0] kernel_data_V_2_10_ret_reg_1036;
reg   [15:0] kernel_data_V_2_11_ret_reg_1041;
reg   [15:0] kernel_data_V_2_16_ret_reg_1046;
reg   [15:0] kernel_data_V_2_17_ret_reg_1051;
reg   [15:0] kernel_data_V_2_18_ret_reg_1056;
reg   [15:0] kernel_data_V_2_19_ret_reg_1061;
reg   [15:0] kernel_data_V_2_20_ret_reg_1066;
reg   [15:0] kernel_data_V_2_21_ret_reg_1071;
reg   [15:0] kernel_data_V_2_22_ret_reg_1076;
reg   [15:0] kernel_data_V_2_23_ret_reg_1081;
reg   [15:0] kernel_data_V_2_28_ret_reg_1086;
reg   [15:0] kernel_data_V_2_29_ret_reg_1091;
reg   [15:0] kernel_data_V_2_30_ret_reg_1096;
reg   [15:0] kernel_data_V_2_31_ret_reg_1101;
reg   [15:0] kernel_data_V_2_32_ret_reg_1106;
reg   [15:0] kernel_data_V_2_33_ret_reg_1111;
reg   [15:0] kernel_data_V_2_34_ret_reg_1116;
reg   [15:0] kernel_data_V_2_35_ret_reg_1121;
wire   [0:0] or_cond2_fu_823_p2;
wire   [0:0] tmp_48_fu_829_p2;
reg   [0:0] tmp_48_reg_1130;
wire   [31:0] p_in_fu_853_p3;
reg   [31:0] p_in_reg_1134;
wire   [0:0] tmp_49_fu_873_p2;
reg   [0:0] tmp_49_reg_1139;
wire   [31:0] p_in1_fu_897_p3;
reg   [31:0] p_in1_reg_1143;
reg   [15:0] tmp_data_0_V_reg_1148;
reg   [15:0] tmp_data_1_V_reg_1153;
reg   [15:0] tmp_data_2_V_reg_1158;
reg   [15:0] tmp_data_3_V_reg_1163;
reg   [15:0] tmp_data_4_V_reg_1168;
reg   [15:0] tmp_data_5_V_reg_1173;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage7_subdone;
wire    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start;
wire    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_done;
wire    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_idle;
wire    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ready;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_0;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_1;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_2;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_3;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_4;
wire   [15:0] grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_5;
reg    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ce;
wire    ap_block_state2_pp0_stage1_iter0_ignore_call0;
wire    ap_block_pp0_stage1_11001_ignoreCallOp127;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage2_iter0_ignore_call0;
wire    ap_block_pp0_stage2_11001_ignoreCallOp132;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage3_iter0_ignore_call0;
wire    ap_block_pp0_stage3_11001_ignoreCallOp135;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state5_pp0_stage4_iter0_ignore_call0;
wire    ap_block_pp0_stage4_11001_ignoreCallOp136;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state6_pp0_stage5_iter0_ignore_call0;
wire    ap_block_pp0_stage5_11001_ignoreCallOp137;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state7_pp0_stage6_iter0_ignore_call0;
wire    ap_block_pp0_stage6_11001_ignoreCallOp138;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state8_pp0_stage7_iter0_ignore_call0;
wire    ap_block_pp0_stage7_11001_ignoreCallOp139;
reg    call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_start;
wire    call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_done;
wire    call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_idle;
wire    call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ready;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_0;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_1;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_2;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_3;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_4;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_5;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_6;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_7;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_8;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_9;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_10;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_11;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_12;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_13;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_14;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_15;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_16;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_17;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_18;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_19;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_20;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_21;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_22;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_23;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_24;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_25;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_26;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_27;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_28;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_29;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_30;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_31;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_32;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_33;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_34;
wire   [15:0] call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_35;
reg    call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ce;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call34;
reg    ap_block_state9_pp0_stage0_iter1_ignore_call34;
reg    ap_block_pp0_stage0_11001_ignoreCallOp38;
reg   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_240;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
reg    grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg;
wire    ap_block_pp0_stage1;
reg    res_stream_V_data_0_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] tmp_51_fu_879_p2;
wire   [31:0] tmp_50_fu_835_p2;
wire   [30:0] tmp_458_fu_775_p4;
wire   [30:0] tmp_459_fu_795_p4;
wire   [0:0] tmp_s_fu_755_p2;
wire   [0:0] tmp_45_fu_765_p2;
wire   [0:0] icmp_fu_785_p2;
wire   [0:0] icmp7_fu_805_p2;
wire   [0:0] tmp1_fu_817_p2;
wire   [0:0] tmp_fu_811_p2;
wire   [31:0] phitmp_fu_847_p2;
wire   [31:0] phitmp1_fu_891_p2;
wire    ap_block_pp0_stage7;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
wire    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_subdone;
wire    ap_block_state5_pp0_stage4_iter0;
reg    ap_block_pp0_stage4_subdone;
wire    ap_block_state6_pp0_stage5_iter0;
reg    ap_block_pp0_stage5_subdone;
wire    ap_block_state7_pp0_stage6_iter0;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
reg    ap_condition_2078;
reg    ap_condition_486;
reg    ap_condition_2085;
reg    ap_condition_2090;
reg    ap_condition_2084;
reg    ap_condition_2095;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 kernel_data_V_2_4 = 16'd0;
#0 kernel_data_V_2_5 = 16'd0;
#0 kernel_data_V_2_6 = 16'd0;
#0 kernel_data_V_2_7 = 16'd0;
#0 kernel_data_V_2_8 = 16'd0;
#0 kernel_data_V_2_9 = 16'd0;
#0 kernel_data_V_2_10 = 16'd0;
#0 kernel_data_V_2_11 = 16'd0;
#0 kernel_data_V_2_16 = 16'd0;
#0 kernel_data_V_2_17 = 16'd0;
#0 kernel_data_V_2_18 = 16'd0;
#0 kernel_data_V_2_19 = 16'd0;
#0 kernel_data_V_2_20 = 16'd0;
#0 kernel_data_V_2_21 = 16'd0;
#0 kernel_data_V_2_22 = 16'd0;
#0 kernel_data_V_2_23 = 16'd0;
#0 kernel_data_V_2_28 = 16'd0;
#0 kernel_data_V_2_29 = 16'd0;
#0 kernel_data_V_2_30 = 16'd0;
#0 kernel_data_V_2_31 = 16'd0;
#0 kernel_data_V_2_32 = 16'd0;
#0 kernel_data_V_2_33 = 16'd0;
#0 kernel_data_V_2_34 = 16'd0;
#0 kernel_data_V_2_35 = 16'd0;
#0 sX_3 = 32'd0;
#0 sY_3 = 32'd0;
#0 pY_3 = 32'd0;
#0 pX_3 = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg = 1'b0;
end

dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0 grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start),
    .ap_done(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_done),
    .ap_idle(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_idle),
    .ap_ready(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ready),
    .data_0_V_read(kernel_data_V_2_4_1_1_reg_1001),
    .data_1_V_read(kernel_data_V_2_10_1_reg_996),
    .data_2_V_read(kernel_data_V_2_9_1_reg_991),
    .data_3_V_read(kernel_data_V_2_8_1_reg_986),
    .data_4_V_read(kernel_data_V_2_4_ret_reg_1006),
    .data_5_V_read(kernel_data_V_2_5_ret_reg_1011),
    .data_6_V_read(kernel_data_V_2_6_ret_reg_1016),
    .data_7_V_read(kernel_data_V_2_7_ret_reg_1021),
    .data_8_V_read(kernel_data_V_2_8_ret_reg_1026),
    .data_9_V_read(kernel_data_V_2_9_ret_reg_1031),
    .data_10_V_read(kernel_data_V_2_10_ret_reg_1036),
    .data_11_V_read(kernel_data_V_2_11_ret_reg_1041),
    .data_12_V_read(kernel_data_V_2_7_1_reg_981),
    .data_13_V_read(kernel_data_V_2_6_1_reg_976),
    .data_14_V_read(kernel_data_V_2_5_1_reg_971),
    .data_15_V_read(kernel_data_V_2_4_1_reg_966),
    .data_16_V_read(kernel_data_V_2_16_ret_reg_1046),
    .data_17_V_read(kernel_data_V_2_17_ret_reg_1051),
    .data_18_V_read(kernel_data_V_2_18_ret_reg_1056),
    .data_19_V_read(kernel_data_V_2_19_ret_reg_1061),
    .data_20_V_read(kernel_data_V_2_20_ret_reg_1066),
    .data_21_V_read(kernel_data_V_2_21_ret_reg_1071),
    .data_22_V_read(kernel_data_V_2_22_ret_reg_1076),
    .data_23_V_read(kernel_data_V_2_23_ret_reg_1081),
    .data_24_V_read(kernel_data_V_2_3_reg_961),
    .data_25_V_read(kernel_data_V_2_2_reg_956),
    .data_26_V_read(kernel_data_V_2_1_reg_951),
    .data_27_V_read(kernel_data_V_2_s_reg_946),
    .data_28_V_read(kernel_data_V_2_28_ret_reg_1086),
    .data_29_V_read(kernel_data_V_2_29_ret_reg_1091),
    .data_30_V_read(kernel_data_V_2_30_ret_reg_1096),
    .data_31_V_read(kernel_data_V_2_31_ret_reg_1101),
    .data_32_V_read(kernel_data_V_2_32_ret_reg_1106),
    .data_33_V_read(kernel_data_V_2_33_ret_reg_1111),
    .data_34_V_read(kernel_data_V_2_34_ret_reg_1116),
    .data_35_V_read(kernel_data_V_2_35_ret_reg_1121),
    .ap_return_0(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_0),
    .ap_return_1(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_1),
    .ap_return_2(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_2),
    .ap_return_3(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_3),
    .ap_return_4(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_4),
    .ap_return_5(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_5),
    .ap_ce(grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ce)
);

shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_start),
    .ap_done(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_done),
    .ap_idle(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_idle),
    .ap_ready(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ready),
    .in_elem_data_0_V_read(in_elem_data_0_V_read),
    .in_elem_data_1_V_read(in_elem_data_1_V_read),
    .in_elem_data_2_V_read(in_elem_data_2_V_read),
    .in_elem_data_3_V_read(in_elem_data_3_V_read),
    .kernel_window_4_V_read(kernel_data_V_2_4),
    .kernel_window_5_V_read(kernel_data_V_2_5),
    .kernel_window_6_V_read(kernel_data_V_2_6),
    .kernel_window_7_V_read(kernel_data_V_2_7),
    .kernel_window_8_V_read(kernel_data_V_2_8),
    .kernel_window_9_V_read(kernel_data_V_2_9),
    .kernel_window_10_V_read(kernel_data_V_2_10),
    .kernel_window_11_V_read(kernel_data_V_2_11),
    .kernel_window_16_V_read(kernel_data_V_2_16),
    .kernel_window_17_V_read(kernel_data_V_2_17),
    .kernel_window_18_V_read(kernel_data_V_2_18),
    .kernel_window_19_V_read(kernel_data_V_2_19),
    .kernel_window_20_V_read(kernel_data_V_2_20),
    .kernel_window_21_V_read(kernel_data_V_2_21),
    .kernel_window_22_V_read(kernel_data_V_2_22),
    .kernel_window_23_V_read(kernel_data_V_2_23),
    .kernel_window_28_V_read(kernel_data_V_2_28),
    .kernel_window_29_V_read(kernel_data_V_2_29),
    .kernel_window_30_V_read(kernel_data_V_2_30),
    .kernel_window_31_V_read(kernel_data_V_2_31),
    .kernel_window_32_V_read(kernel_data_V_2_32),
    .kernel_window_33_V_read(kernel_data_V_2_33),
    .kernel_window_34_V_read(kernel_data_V_2_34),
    .kernel_window_35_V_read(kernel_data_V_2_35),
    .ap_return_0(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_0),
    .ap_return_1(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_1),
    .ap_return_2(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_2),
    .ap_return_3(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_3),
    .ap_return_4(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_4),
    .ap_return_5(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_5),
    .ap_return_6(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_6),
    .ap_return_7(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_7),
    .ap_return_8(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_8),
    .ap_return_9(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_9),
    .ap_return_10(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_10),
    .ap_return_11(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_11),
    .ap_return_12(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_12),
    .ap_return_13(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_13),
    .ap_return_14(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_14),
    .ap_return_15(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_15),
    .ap_return_16(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_16),
    .ap_return_17(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_17),
    .ap_return_18(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_18),
    .ap_return_19(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_19),
    .ap_return_20(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_20),
    .ap_return_21(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_21),
    .ap_return_22(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_22),
    .ap_return_23(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_23),
    .ap_return_24(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_24),
    .ap_return_25(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_25),
    .ap_return_26(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_26),
    .ap_return_27(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_27),
    .ap_return_28(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_28),
    .ap_return_29(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_29),
    .ap_return_30(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_30),
    .ap_return_31(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_31),
    .ap_return_32(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_32),
    .ap_return_33(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_33),
    .ap_return_34(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_34),
    .ap_return_35(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_35),
    .ap_ce(call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ce)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond2_fu_823_p2 == 1'd1))) begin
            grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ready == 1'b1)) begin
            grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_2078)) begin
        if ((tmp_49_reg_1139 == 1'd1)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_240 <= 32'd0;
        end else if ((tmp_49_reg_1139 == 1'd0)) begin
            ap_phi_reg_pp0_iter0_storemerge_reg_240 <= p_in1_reg_1143;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_486)) begin
        if ((tmp_48_fu_829_p2 == 1'd1)) begin
            pX_3 <= 32'd0;
        end else if ((tmp_48_fu_829_p2 == 1'd0)) begin
            pX_3 <= tmp_50_fu_835_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_2090)) begin
            pY_3 <= 32'd0;
        end else if ((1'b1 == ap_condition_2085)) begin
            pY_3 <= tmp_51_fu_879_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if ((1'b1 == ap_condition_2095)) begin
            sX_3 <= p_in_reg_1134;
        end else if ((1'b1 == ap_condition_2084)) begin
            sX_3 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_data_V_2_10 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_18;
        kernel_data_V_2_11 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_19;
        kernel_data_V_2_16 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_20;
        kernel_data_V_2_17 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_21;
        kernel_data_V_2_18 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_22;
        kernel_data_V_2_19 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_23;
        kernel_data_V_2_20 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_24;
        kernel_data_V_2_21 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_25;
        kernel_data_V_2_22 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_26;
        kernel_data_V_2_23 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_27;
        kernel_data_V_2_28 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_28;
        kernel_data_V_2_29 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_29;
        kernel_data_V_2_30 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_30;
        kernel_data_V_2_31 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_31;
        kernel_data_V_2_32 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_32;
        kernel_data_V_2_33 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_33;
        kernel_data_V_2_34 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_34;
        kernel_data_V_2_35 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_35;
        kernel_data_V_2_4 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_12;
        kernel_data_V_2_5 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_13;
        kernel_data_V_2_6 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_14;
        kernel_data_V_2_7 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_15;
        kernel_data_V_2_8 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_16;
        kernel_data_V_2_9 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_17;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kernel_data_V_2_10_1_reg_996 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_1;
        kernel_data_V_2_10_ret_reg_1036 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_18;
        kernel_data_V_2_11_ret_reg_1041 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_19;
        kernel_data_V_2_16_ret_reg_1046 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_20;
        kernel_data_V_2_17_ret_reg_1051 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_21;
        kernel_data_V_2_18_ret_reg_1056 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_22;
        kernel_data_V_2_19_ret_reg_1061 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_23;
        kernel_data_V_2_1_reg_951 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_10;
        kernel_data_V_2_20_ret_reg_1066 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_24;
        kernel_data_V_2_21_ret_reg_1071 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_25;
        kernel_data_V_2_22_ret_reg_1076 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_26;
        kernel_data_V_2_23_ret_reg_1081 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_27;
        kernel_data_V_2_28_ret_reg_1086 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_28;
        kernel_data_V_2_29_ret_reg_1091 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_29;
        kernel_data_V_2_2_reg_956 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_9;
        kernel_data_V_2_30_ret_reg_1096 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_30;
        kernel_data_V_2_31_ret_reg_1101 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_31;
        kernel_data_V_2_32_ret_reg_1106 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_32;
        kernel_data_V_2_33_ret_reg_1111 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_33;
        kernel_data_V_2_34_ret_reg_1116 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_34;
        kernel_data_V_2_35_ret_reg_1121 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_35;
        kernel_data_V_2_3_reg_961 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_8;
        kernel_data_V_2_4_1_1_reg_1001 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_0;
        kernel_data_V_2_4_1_reg_966 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_7;
        kernel_data_V_2_4_ret_reg_1006 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_12;
        kernel_data_V_2_5_1_reg_971 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_6;
        kernel_data_V_2_5_ret_reg_1011 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_13;
        kernel_data_V_2_6_1_reg_976 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_5;
        kernel_data_V_2_6_ret_reg_1016 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_14;
        kernel_data_V_2_7_1_reg_981 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_4;
        kernel_data_V_2_7_ret_reg_1021 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_15;
        kernel_data_V_2_8_1_reg_986 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_3;
        kernel_data_V_2_8_ret_reg_1026 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_16;
        kernel_data_V_2_9_1_reg_991 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_2;
        kernel_data_V_2_9_ret_reg_1031 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_17;
        kernel_data_V_2_s_reg_946 <= call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_return_11;
        or_cond2_reg_1126 <= or_cond2_fu_823_p2;
        tmp_48_reg_1130 <= tmp_48_fu_829_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (tmp_49_fu_873_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_48_fu_829_p2 == 1'd1))) begin
        p_in1_reg_1143 <= p_in1_fu_897_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (tmp_48_fu_829_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_in_reg_1134 <= p_in_fu_853_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_48_reg_1130 == 1'd1))) begin
        sY_3 <= ap_phi_reg_pp0_iter0_storemerge_reg_240;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_48_fu_829_p2 == 1'd1))) begin
        tmp_49_reg_1139 <= tmp_49_fu_873_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (or_cond2_reg_1126 == 1'd1))) begin
        tmp_data_0_V_reg_1148 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_0;
        tmp_data_1_V_reg_1153 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_1;
        tmp_data_2_V_reg_1158 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_2;
        tmp_data_3_V_reg_1163 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_3;
        tmp_data_4_V_reg_1168 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_4;
        tmp_data_5_V_reg_1173 <= grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_return_5;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp38) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ce = 1'b1;
    end else begin
        call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b1))) begin
        call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_start = 1'b1;
    end else begin
        call_ret1_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config10_s_fu_291_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (((1'b0 == ap_block_pp0_stage7_11001_ignoreCallOp139) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001_ignoreCallOp138) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001_ignoreCallOp137) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001_ignoreCallOp136) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001_ignoreCallOp135) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001_ignoreCallOp132) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001_ignoreCallOp127) & (1'b1 == ap_CS_fsm_pp0_stage1))))) begin
        grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ce = 1'b1;
    end else begin
        grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_0_V1_update = 1'b1;
    end else begin
        res_stream_V_data_0_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_0_V_blk_n = res_stream_V_data_0_V_full_n;
    end else begin
        res_stream_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_1_V_blk_n = res_stream_V_data_1_V_full_n;
    end else begin
        res_stream_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_2_V_blk_n = res_stream_V_data_2_V_full_n;
    end else begin
        res_stream_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_3_V_blk_n = res_stream_V_data_3_V_full_n;
    end else begin
        res_stream_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_4_V_blk_n = res_stream_V_data_4_V_full_n;
    end else begin
        res_stream_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_cond2_reg_1126 == 1'd1))) begin
        res_stream_V_data_5_V_blk_n = res_stream_V_data_5_V_full_n;
    end else begin
        res_stream_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((res_stream_V_data_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_cond2_reg_1126 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((res_stream_V_data_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_cond2_reg_1126 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp38 = (((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((res_stream_V_data_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_cond2_reg_1126 == 1'd1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((res_stream_V_data_0_V1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (or_cond2_reg_1126 == 1'd1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_ignoreCallOp127 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_ignoreCallOp132 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3_11001_ignoreCallOp135 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage4_11001_ignoreCallOp136 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage5_11001_ignoreCallOp137 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage6_11001_ignoreCallOp138 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001_ignoreCallOp139 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call34 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = ((res_stream_V_data_0_V1_status == 1'b0) & (or_cond2_reg_1126 == 1'd1));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1_ignore_call34 = ((res_stream_V_data_0_V1_status == 1'b0) & (or_cond2_reg_1126 == 1'd1));
end

always @ (*) begin
    ap_condition_2078 = ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_48_reg_1130 == 1'd1));
end

always @ (*) begin
    ap_condition_2084 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_48_fu_829_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_2085 = ((tmp_49_fu_873_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (tmp_48_fu_829_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_2090 = ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (tmp_49_reg_1139 == 1'd1) & (tmp_48_reg_1130 == 1'd1));
end

always @ (*) begin
    ap_condition_2095 = ((1'b0 == ap_block_pp0_stage1_11001) & (tmp_48_reg_1130 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_condition_486 = ((1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start = grp_dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config10_mult_0_0_0_0_0_0_0_fu_251_ap_start_reg;

assign icmp7_fu_805_p2 = (($signed(tmp_459_fu_795_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_fu_785_p2 = (($signed(tmp_458_fu_775_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign or_cond2_fu_823_p2 = (tmp_fu_811_p2 & tmp1_fu_817_p2);

assign p_in1_fu_897_p3 = ((tmp_45_fu_765_p2[0:0] === 1'b1) ? 32'd1 : phitmp1_fu_891_p2);

assign p_in_fu_853_p3 = ((tmp_s_fu_755_p2[0:0] === 1'b1) ? 32'd1 : phitmp_fu_847_p2);

assign phitmp1_fu_891_p2 = (sY_3 + 32'd1);

assign phitmp_fu_847_p2 = (sX_3 + 32'd1);

assign res_stream_V_data_0_V1_status = (res_stream_V_data_5_V_full_n & res_stream_V_data_4_V_full_n & res_stream_V_data_3_V_full_n & res_stream_V_data_2_V_full_n & res_stream_V_data_1_V_full_n & res_stream_V_data_0_V_full_n);

assign res_stream_V_data_0_V_din = tmp_data_0_V_reg_1148;

assign res_stream_V_data_0_V_write = res_stream_V_data_0_V1_update;

assign res_stream_V_data_1_V_din = tmp_data_1_V_reg_1153;

assign res_stream_V_data_1_V_write = res_stream_V_data_0_V1_update;

assign res_stream_V_data_2_V_din = tmp_data_2_V_reg_1158;

assign res_stream_V_data_2_V_write = res_stream_V_data_0_V1_update;

assign res_stream_V_data_3_V_din = tmp_data_3_V_reg_1163;

assign res_stream_V_data_3_V_write = res_stream_V_data_0_V1_update;

assign res_stream_V_data_4_V_din = tmp_data_4_V_reg_1168;

assign res_stream_V_data_4_V_write = res_stream_V_data_0_V1_update;

assign res_stream_V_data_5_V_din = tmp_data_5_V_reg_1173;

assign res_stream_V_data_5_V_write = res_stream_V_data_0_V1_update;

assign tmp1_fu_817_p2 = (icmp_fu_785_p2 & icmp7_fu_805_p2);

assign tmp_458_fu_775_p4 = {{pY_3[31:1]}};

assign tmp_459_fu_795_p4 = {{pX_3[31:1]}};

assign tmp_45_fu_765_p2 = ((sY_3 == 32'd2) ? 1'b1 : 1'b0);

assign tmp_48_fu_829_p2 = ((pX_3 == 32'd8) ? 1'b1 : 1'b0);

assign tmp_49_fu_873_p2 = ((pY_3 == 32'd6) ? 1'b1 : 1'b0);

assign tmp_50_fu_835_p2 = (pX_3 + 32'd1);

assign tmp_51_fu_879_p2 = (pY_3 + 32'd1);

assign tmp_fu_811_p2 = (tmp_s_fu_755_p2 & tmp_45_fu_765_p2);

assign tmp_s_fu_755_p2 = ((sX_3 == 32'd2) ? 1'b1 : 1'b0);

endmodule //compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_6u_config10_s
