// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module softmax_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        res_V_data_0_V_TDATA,
        res_V_data_0_V_TVALID,
        res_V_data_0_V_TREADY,
        res_V_data_1_V_TDATA,
        res_V_data_1_V_TVALID,
        res_V_data_1_V_TREADY,
        res_V_data_2_V_TDATA,
        res_V_data_2_V_TVALID,
        res_V_data_2_V_TREADY,
        res_V_data_3_V_TDATA,
        res_V_data_3_V_TVALID,
        res_V_data_3_V_TREADY
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [15:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [15:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [15:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
output  [15:0] res_V_data_0_V_TDATA;
output   res_V_data_0_V_TVALID;
input   res_V_data_0_V_TREADY;
output  [15:0] res_V_data_1_V_TDATA;
output   res_V_data_1_V_TVALID;
input   res_V_data_1_V_TREADY;
output  [15:0] res_V_data_2_V_TDATA;
output   res_V_data_2_V_TVALID;
input   res_V_data_2_V_TREADY;
output  [15:0] res_V_data_3_V_TDATA;
output   res_V_data_3_V_TVALID;
input   res_V_data_3_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] res_V_data_0_V_1_data_out;
wire    res_V_data_0_V_1_vld_in;
wire    res_V_data_0_V_1_vld_out;
wire    res_V_data_0_V_1_ack_in;
wire    res_V_data_0_V_1_ack_out;
reg   [15:0] res_V_data_0_V_1_payload_A;
reg   [15:0] res_V_data_0_V_1_payload_B;
reg    res_V_data_0_V_1_sel_rd;
reg    res_V_data_0_V_1_sel_wr;
wire    res_V_data_0_V_1_sel;
wire    res_V_data_0_V_1_load_A;
wire    res_V_data_0_V_1_load_B;
reg   [1:0] res_V_data_0_V_1_state;
wire    res_V_data_0_V_1_state_cmp_full;
reg   [15:0] res_V_data_1_V_1_data_out;
wire    res_V_data_1_V_1_vld_in;
wire    res_V_data_1_V_1_vld_out;
wire    res_V_data_1_V_1_ack_in;
wire    res_V_data_1_V_1_ack_out;
reg   [15:0] res_V_data_1_V_1_payload_A;
reg   [15:0] res_V_data_1_V_1_payload_B;
reg    res_V_data_1_V_1_sel_rd;
reg    res_V_data_1_V_1_sel_wr;
wire    res_V_data_1_V_1_sel;
wire    res_V_data_1_V_1_load_A;
wire    res_V_data_1_V_1_load_B;
reg   [1:0] res_V_data_1_V_1_state;
wire    res_V_data_1_V_1_state_cmp_full;
reg   [15:0] res_V_data_2_V_1_data_out;
wire    res_V_data_2_V_1_vld_in;
wire    res_V_data_2_V_1_vld_out;
wire    res_V_data_2_V_1_ack_in;
wire    res_V_data_2_V_1_ack_out;
reg   [15:0] res_V_data_2_V_1_payload_A;
reg   [15:0] res_V_data_2_V_1_payload_B;
reg    res_V_data_2_V_1_sel_rd;
reg    res_V_data_2_V_1_sel_wr;
wire    res_V_data_2_V_1_sel;
wire    res_V_data_2_V_1_load_A;
wire    res_V_data_2_V_1_load_B;
reg   [1:0] res_V_data_2_V_1_state;
wire    res_V_data_2_V_1_state_cmp_full;
reg   [15:0] res_V_data_3_V_1_data_out;
wire    res_V_data_3_V_1_vld_in;
wire    res_V_data_3_V_1_vld_out;
wire    res_V_data_3_V_1_ack_in;
wire    res_V_data_3_V_1_ack_out;
reg   [15:0] res_V_data_3_V_1_payload_A;
reg   [15:0] res_V_data_3_V_1_payload_B;
reg    res_V_data_3_V_1_sel_rd;
reg    res_V_data_3_V_1_sel_wr;
wire    res_V_data_3_V_1_sel;
wire    res_V_data_3_V_1_load_A;
wire    res_V_data_3_V_1_load_B;
reg   [1:0] res_V_data_3_V_1_state;
wire    res_V_data_3_V_1_state_cmp_full;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_state20;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n;
reg    data_V_data_1_V_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n;
reg    data_V_data_2_V_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n;
reg    data_V_data_3_V_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n;
reg    res_V_data_0_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n;
reg    res_V_data_1_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n;
reg    res_V_data_2_V_TDATA_blk_n;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n;
reg    res_V_data_3_V_TDATA_blk_n;
reg    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_start;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_done;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_idle;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_ready;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TREADY;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_read;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_read;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_read;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_read;
wire   [15:0] grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TVALID;
wire   [15:0] grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TVALID;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TVALID;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TREADY;
wire   [15:0] grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TVALID;
wire    grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TREADY;
reg    ap_block_state1_ignore_call8;
wire    ap_CS_fsm_state21;
reg    ap_block_state21;
reg   [20:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_block_state20;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 21'd1;
#0 res_V_data_0_V_1_sel_rd = 1'b0;
#0 res_V_data_0_V_1_sel_wr = 1'b0;
#0 res_V_data_0_V_1_state = 2'd0;
#0 res_V_data_1_V_1_sel_rd = 1'b0;
#0 res_V_data_1_V_1_sel_wr = 1'b0;
#0 res_V_data_1_V_1_state = 2'd0;
#0 res_V_data_2_V_1_sel_rd = 1'b0;
#0 res_V_data_2_V_1_sel_wr = 1'b0;
#0 res_V_data_2_V_1_state = 2'd0;
#0 res_V_data_3_V_1_sel_rd = 1'b0;
#0 res_V_data_3_V_1_sel_wr = 1'b0;
#0 res_V_data_3_V_1_state = 2'd0;
end

softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_start),
    .ap_done(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_done),
    .ap_idle(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_idle),
    .ap_ready(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_ready),
    .res_V_data_0_V_TREADY(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TREADY),
    .data_V_data_0_V_dout(data_V_data_0_V_dout),
    .data_V_data_0_V_empty_n(data_V_data_0_V_empty_n),
    .data_V_data_0_V_read(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_read),
    .data_V_data_1_V_dout(data_V_data_1_V_dout),
    .data_V_data_1_V_empty_n(data_V_data_1_V_empty_n),
    .data_V_data_1_V_read(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_read),
    .data_V_data_2_V_dout(data_V_data_2_V_dout),
    .data_V_data_2_V_empty_n(data_V_data_2_V_empty_n),
    .data_V_data_2_V_read(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_read),
    .data_V_data_3_V_dout(data_V_data_3_V_dout),
    .data_V_data_3_V_empty_n(data_V_data_3_V_empty_n),
    .data_V_data_3_V_read(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_read),
    .res_V_data_0_V_TDATA(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA),
    .res_V_data_0_V_TVALID(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TVALID),
    .res_V_data_1_V_TDATA(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA),
    .res_V_data_1_V_TVALID(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TVALID),
    .res_V_data_1_V_TREADY(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TREADY),
    .res_V_data_2_V_TDATA(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA),
    .res_V_data_2_V_TVALID(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TVALID),
    .res_V_data_2_V_TREADY(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TREADY),
    .res_V_data_3_V_TDATA(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA),
    .res_V_data_3_V_TVALID(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TVALID),
    .res_V_data_3_V_TREADY(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TREADY),
    .data_V_data_0_V_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n),
    .data_V_data_1_V_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n),
    .data_V_data_2_V_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n),
    .data_V_data_3_V_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n),
    .res_V_data_0_V_TDATA_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n),
    .res_V_data_1_V_TDATA_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n),
    .res_V_data_2_V_TDATA_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n),
    .res_V_data_3_V_TDATA_blk_n(grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((res_V_data_0_V_1_ack_in == 1'b0) | (res_V_data_3_V_1_ack_in == 1'b0) | (res_V_data_2_V_1_ack_in == 1'b0) | (res_V_data_1_V_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state21))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_0_V_1_ack_out == 1'b1) & (res_V_data_0_V_1_vld_out == 1'b1))) begin
            res_V_data_0_V_1_sel_rd <= ~res_V_data_0_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_0_V_1_ack_in == 1'b1) & (res_V_data_0_V_1_vld_in == 1'b1))) begin
            res_V_data_0_V_1_sel_wr <= ~res_V_data_0_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_0_V_1_state == 2'd2) & (res_V_data_0_V_1_vld_in == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_1_vld_in == 1'b0) & (res_V_data_0_V_1_ack_out == 1'b1)))) begin
            res_V_data_0_V_1_state <= 2'd2;
        end else if ((((res_V_data_0_V_1_state == 2'd1) & (res_V_data_0_V_1_ack_out == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_1_ack_out == 1'b0) & (res_V_data_0_V_1_vld_in == 1'b1)))) begin
            res_V_data_0_V_1_state <= 2'd1;
        end else if (((~((res_V_data_0_V_1_ack_out == 1'b0) & (res_V_data_0_V_1_vld_in == 1'b1)) & ~((res_V_data_0_V_1_vld_in == 1'b0) & (res_V_data_0_V_1_ack_out == 1'b1)) & (res_V_data_0_V_1_state == 2'd3)) | ((res_V_data_0_V_1_state == 2'd1) & (res_V_data_0_V_1_ack_out == 1'b1)) | ((res_V_data_0_V_1_state == 2'd2) & (res_V_data_0_V_1_vld_in == 1'b1)))) begin
            res_V_data_0_V_1_state <= 2'd3;
        end else begin
            res_V_data_0_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_1_V_1_ack_out == 1'b1) & (res_V_data_1_V_1_vld_out == 1'b1))) begin
            res_V_data_1_V_1_sel_rd <= ~res_V_data_1_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_1_V_1_ack_in == 1'b1) & (res_V_data_1_V_1_vld_in == 1'b1))) begin
            res_V_data_1_V_1_sel_wr <= ~res_V_data_1_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_1_V_1_state == 2'd2) & (res_V_data_1_V_1_vld_in == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_1_vld_in == 1'b0) & (res_V_data_1_V_1_ack_out == 1'b1)))) begin
            res_V_data_1_V_1_state <= 2'd2;
        end else if ((((res_V_data_1_V_1_state == 2'd1) & (res_V_data_1_V_1_ack_out == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_1_ack_out == 1'b0) & (res_V_data_1_V_1_vld_in == 1'b1)))) begin
            res_V_data_1_V_1_state <= 2'd1;
        end else if (((~((res_V_data_1_V_1_vld_in == 1'b0) & (res_V_data_1_V_1_ack_out == 1'b1)) & ~((res_V_data_1_V_1_ack_out == 1'b0) & (res_V_data_1_V_1_vld_in == 1'b1)) & (res_V_data_1_V_1_state == 2'd3)) | ((res_V_data_1_V_1_state == 2'd1) & (res_V_data_1_V_1_ack_out == 1'b1)) | ((res_V_data_1_V_1_state == 2'd2) & (res_V_data_1_V_1_vld_in == 1'b1)))) begin
            res_V_data_1_V_1_state <= 2'd3;
        end else begin
            res_V_data_1_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_2_V_1_ack_out == 1'b1) & (res_V_data_2_V_1_vld_out == 1'b1))) begin
            res_V_data_2_V_1_sel_rd <= ~res_V_data_2_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_2_V_1_ack_in == 1'b1) & (res_V_data_2_V_1_vld_in == 1'b1))) begin
            res_V_data_2_V_1_sel_wr <= ~res_V_data_2_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_2_V_1_state == 2'd2) & (res_V_data_2_V_1_vld_in == 1'b0)) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_1_vld_in == 1'b0) & (res_V_data_2_V_1_ack_out == 1'b1)))) begin
            res_V_data_2_V_1_state <= 2'd2;
        end else if ((((res_V_data_2_V_1_state == 2'd1) & (res_V_data_2_V_1_ack_out == 1'b0)) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_1_ack_out == 1'b0) & (res_V_data_2_V_1_vld_in == 1'b1)))) begin
            res_V_data_2_V_1_state <= 2'd1;
        end else if (((~((res_V_data_2_V_1_vld_in == 1'b0) & (res_V_data_2_V_1_ack_out == 1'b1)) & ~((res_V_data_2_V_1_ack_out == 1'b0) & (res_V_data_2_V_1_vld_in == 1'b1)) & (res_V_data_2_V_1_state == 2'd3)) | ((res_V_data_2_V_1_state == 2'd1) & (res_V_data_2_V_1_ack_out == 1'b1)) | ((res_V_data_2_V_1_state == 2'd2) & (res_V_data_2_V_1_vld_in == 1'b1)))) begin
            res_V_data_2_V_1_state <= 2'd3;
        end else begin
            res_V_data_2_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_3_V_1_ack_out == 1'b1) & (res_V_data_3_V_1_vld_out == 1'b1))) begin
            res_V_data_3_V_1_sel_rd <= ~res_V_data_3_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_3_V_1_ack_in == 1'b1) & (res_V_data_3_V_1_vld_in == 1'b1))) begin
            res_V_data_3_V_1_sel_wr <= ~res_V_data_3_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_3_V_1_state == 2'd2) & (res_V_data_3_V_1_vld_in == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_1_vld_in == 1'b0) & (res_V_data_3_V_1_ack_out == 1'b1)))) begin
            res_V_data_3_V_1_state <= 2'd2;
        end else if ((((res_V_data_3_V_1_state == 2'd1) & (res_V_data_3_V_1_ack_out == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_1_ack_out == 1'b0) & (res_V_data_3_V_1_vld_in == 1'b1)))) begin
            res_V_data_3_V_1_state <= 2'd1;
        end else if (((~((res_V_data_3_V_1_vld_in == 1'b0) & (res_V_data_3_V_1_ack_out == 1'b1)) & ~((res_V_data_3_V_1_ack_out == 1'b0) & (res_V_data_3_V_1_vld_in == 1'b1)) & (res_V_data_3_V_1_state == 2'd3)) | ((res_V_data_3_V_1_state == 2'd1) & (res_V_data_3_V_1_ack_out == 1'b1)) | ((res_V_data_3_V_1_state == 2'd2) & (res_V_data_3_V_1_vld_in == 1'b1)))) begin
            res_V_data_3_V_1_state <= 2'd3;
        end else begin
            res_V_data_3_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_0_V_1_load_A == 1'b1)) begin
        res_V_data_0_V_1_payload_A <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_0_V_1_load_B == 1'b1)) begin
        res_V_data_0_V_1_payload_B <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_1_V_1_load_A == 1'b1)) begin
        res_V_data_1_V_1_payload_A <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_1_V_1_load_B == 1'b1)) begin
        res_V_data_1_V_1_payload_B <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_2_V_1_load_A == 1'b1)) begin
        res_V_data_2_V_1_payload_A <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_2_V_1_load_B == 1'b1)) begin
        res_V_data_2_V_1_payload_B <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_3_V_1_load_A == 1'b1)) begin
        res_V_data_3_V_1_payload_A <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_3_V_1_load_B == 1'b1)) begin
        res_V_data_3_V_1_payload_B <= grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA;
    end
end

always @ (*) begin
    if ((~((res_V_data_0_V_1_ack_in == 1'b0) | (res_V_data_3_V_1_ack_in == 1'b0) | (res_V_data_2_V_1_ack_in == 1'b0) | (res_V_data_1_V_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((res_V_data_0_V_1_ack_in == 1'b0) | (res_V_data_3_V_1_ack_in == 1'b0) | (res_V_data_2_V_1_ack_in == 1'b0) | (res_V_data_1_V_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state21))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_0_V_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_0_V_read = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_read;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_1_V_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_1_V_read = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_read;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_2_V_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_2_V_read = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_read;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        data_V_data_3_V_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_V_data_3_V_read = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_read;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_start = 1'b1;
    end else begin
        grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((res_V_data_0_V_1_sel == 1'b1)) begin
        res_V_data_0_V_1_data_out = res_V_data_0_V_1_payload_B;
    end else begin
        res_V_data_0_V_1_data_out = res_V_data_0_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_0_V_TDATA_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n;
    end else begin
        res_V_data_0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_1_V_1_sel == 1'b1)) begin
        res_V_data_1_V_1_data_out = res_V_data_1_V_1_payload_B;
    end else begin
        res_V_data_1_V_1_data_out = res_V_data_1_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_1_V_TDATA_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n;
    end else begin
        res_V_data_1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_2_V_1_sel == 1'b1)) begin
        res_V_data_2_V_1_data_out = res_V_data_2_V_1_payload_B;
    end else begin
        res_V_data_2_V_1_data_out = res_V_data_2_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_2_V_TDATA_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n;
    end else begin
        res_V_data_2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_3_V_1_sel == 1'b1)) begin
        res_V_data_3_V_1_data_out = res_V_data_3_V_1_payload_B;
    end else begin
        res_V_data_3_V_1_data_out = res_V_data_3_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_V_data_3_V_TDATA_blk_n = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n;
    end else begin
        res_V_data_3_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if ((~((grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n == 1'b0)) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            if ((~((res_V_data_0_V_1_ack_in == 1'b0) | (res_V_data_3_V_1_ack_in == 1'b0) | (res_V_data_2_V_1_ack_in == 1'b0) | (res_V_data_1_V_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call8 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state20 = ((grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TDATA_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_3_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_2_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_1_V_blk_n == 1'b0) | (grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_data_V_data_0_V_blk_n == 1'b0));
end

always @ (*) begin
    ap_block_state21 = ((res_V_data_0_V_1_ack_in == 1'b0) | (res_V_data_3_V_1_ack_in == 1'b0) | (res_V_data_2_V_1_ack_in == 1'b0) | (res_V_data_1_V_1_ack_in == 1'b0));
end

assign grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TREADY = (res_V_data_0_V_1_ack_in & ap_CS_fsm_state20);

assign grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TREADY = (res_V_data_1_V_1_ack_in & ap_CS_fsm_state20);

assign grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TREADY = (res_V_data_2_V_1_ack_in & ap_CS_fsm_state20);

assign grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TREADY = (res_V_data_3_V_1_ack_in & ap_CS_fsm_state20);

assign res_V_data_0_V_1_ack_in = res_V_data_0_V_1_state[1'd1];

assign res_V_data_0_V_1_ack_out = res_V_data_0_V_TREADY;

assign res_V_data_0_V_1_load_A = (res_V_data_0_V_1_state_cmp_full & ~res_V_data_0_V_1_sel_wr);

assign res_V_data_0_V_1_load_B = (res_V_data_0_V_1_state_cmp_full & res_V_data_0_V_1_sel_wr);

assign res_V_data_0_V_1_sel = res_V_data_0_V_1_sel_rd;

assign res_V_data_0_V_1_state_cmp_full = ((res_V_data_0_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_0_V_1_vld_in = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_0_V_TVALID;

assign res_V_data_0_V_1_vld_out = res_V_data_0_V_1_state[1'd0];

assign res_V_data_0_V_TDATA = res_V_data_0_V_1_data_out;

assign res_V_data_0_V_TVALID = res_V_data_0_V_1_state[1'd0];

assign res_V_data_1_V_1_ack_in = res_V_data_1_V_1_state[1'd1];

assign res_V_data_1_V_1_ack_out = res_V_data_1_V_TREADY;

assign res_V_data_1_V_1_load_A = (res_V_data_1_V_1_state_cmp_full & ~res_V_data_1_V_1_sel_wr);

assign res_V_data_1_V_1_load_B = (res_V_data_1_V_1_state_cmp_full & res_V_data_1_V_1_sel_wr);

assign res_V_data_1_V_1_sel = res_V_data_1_V_1_sel_rd;

assign res_V_data_1_V_1_state_cmp_full = ((res_V_data_1_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_1_V_1_vld_in = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_1_V_TVALID;

assign res_V_data_1_V_1_vld_out = res_V_data_1_V_1_state[1'd0];

assign res_V_data_1_V_TDATA = res_V_data_1_V_1_data_out;

assign res_V_data_1_V_TVALID = res_V_data_1_V_1_state[1'd0];

assign res_V_data_2_V_1_ack_in = res_V_data_2_V_1_state[1'd1];

assign res_V_data_2_V_1_ack_out = res_V_data_2_V_TREADY;

assign res_V_data_2_V_1_load_A = (res_V_data_2_V_1_state_cmp_full & ~res_V_data_2_V_1_sel_wr);

assign res_V_data_2_V_1_load_B = (res_V_data_2_V_1_state_cmp_full & res_V_data_2_V_1_sel_wr);

assign res_V_data_2_V_1_sel = res_V_data_2_V_1_sel_rd;

assign res_V_data_2_V_1_state_cmp_full = ((res_V_data_2_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_2_V_1_vld_in = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_2_V_TVALID;

assign res_V_data_2_V_1_vld_out = res_V_data_2_V_1_state[1'd0];

assign res_V_data_2_V_TDATA = res_V_data_2_V_1_data_out;

assign res_V_data_2_V_TVALID = res_V_data_2_V_1_state[1'd0];

assign res_V_data_3_V_1_ack_in = res_V_data_3_V_1_state[1'd1];

assign res_V_data_3_V_1_ack_out = res_V_data_3_V_TREADY;

assign res_V_data_3_V_1_load_A = (res_V_data_3_V_1_state_cmp_full & ~res_V_data_3_V_1_sel_wr);

assign res_V_data_3_V_1_load_B = (res_V_data_3_V_1_state_cmp_full & res_V_data_3_V_1_sel_wr);

assign res_V_data_3_V_1_sel = res_V_data_3_V_1_sel_rd;

assign res_V_data_3_V_1_state_cmp_full = ((res_V_data_3_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_3_V_1_vld_in = grp_softmax_stable_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s_fu_88_res_V_data_3_V_TVALID;

assign res_V_data_3_V_1_vld_out = res_V_data_3_V_1_state[1'd0];

assign res_V_data_3_V_TDATA = res_V_data_3_V_1_data_out;

assign res_V_data_3_V_TVALID = res_V_data_3_V_1_state[1'd0];

endmodule //softmax_array_array_ap_fixed_16_6_5_3_0_4u_softmax_config21_s
